### ISSUE TITLE
label_convent tool的代码可能存在问题

### ISSUE THREAD

**Issue by mbkotori** [yatengLG/ISAT#2]
经过标注后，使用标注文件转换器转换成PNG图片时，转换的图片色彩在边缘上会出现渐变。例如背景色黑色（0，0，0）时，类别颜色（0，200，0），在类别颜色和背景颜色相接的地方颜色会出现（0，0-200，0）的过渡色。（比如（0，125，0），实际上应当不存在该种类别和色彩）

这样的标注文件进行深度学习训练时可能会出错。主要问题是导致无法和网络的输出进行对应，难以计算损失函数。一般来说在类别颜色交界的地方应该是直接跳变的。可能是/tools/label_convert.py代码逻辑存在问题。

**Comment by mbkotori** [comment]
源代码和打包好的软件之间是否存在差别，或者是需求库有差异。

本来想用源码模式debug一下，但是源代码下运行标注文件转换器时，按照readme文件操作后都会运行报错。可以打开程序窗体但是一旦进行转换就会报如下错误：

(ISAT) C:\Users\mbkot\Desktop\ISATcode>python main.py
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe
Could not import submodules (exact error was: numpy.core.multiarray failed to import).

There are many reasons for this error the most common one is that you have
either not built the packages or have built (using `python setup.py build`) or
installed them (using `python setup.py install`) and then proceeded to test
mahotas **without changing the current directory**.

Try installing and then changing to another directory before importing mahotas.
Traceback (most recent call last):
  File "C:\Users\mbkot\Desktop\ISATcode\widgets\converter.py", line 74, in apply
    converter.convert(label_path, save_path)
  File "C:\Users\mbkot\Desktop\ISATcode\tools\label_convert.py", line 57, in convert
    mahotas.polygon.fill_polygon(segmentation, img, color=self.category_dict.get(category, {}).get('index', 0))
AttributeError: module 'mahotas' has no attribute 'polygon'

**Comment by yatengLG** [comment]
下班回去看

**Comment by mbkotori** [comment]
太尴尬了。晚上重新检查了两遍，一次windows，一次linux上源码，才发现问题可能不是标签，是我的看图软件有问题。

windows上用的是win10自带的看图软件，然后用QQ截图的拾色器去读，一直有渐变色。

后来第二遍用linux下Gwenview看图软件+Color Picker拾色器，发现缩放到最大时（1600%）边缘就是正常的，所以极有可能是看图软件导致的渐变色，渲染有问题。

把用来测试的标签写了一个遍历色彩的代码，好像也没有看到边缘渐变的颜色...总结下是我闹了个乌龙，实在太抱歉了。

**Comment by mbkotori** [comment]
实测了，windows下换了两个看图软件显示出来的图边缘都有问题，但是同样图片放在linux下查看边缘就是正常的。下回遇到这种问题我还是先用linux/python代码检查一遍，windows的看图软件在边缘上处理可能有点问题。

打扰大佬了，这软件今天使用了下确实不错，整体比Labelme和LabelImgPlus都要好用些。体验很好。

**Comment by yatengLG** [comment]
> 太尴尬了。晚上重新检查了两遍，一次windows，一次linux上源码，才发现问题可能不是标签，是我的看图软件有问题。
> 
> windows上用的是win10自带的看图软件，然后用QQ截图的拾色器去读，一直有渐变色。
> 
> 后来第二遍用linux下Gwenview看图软件+Color Picker拾色器，发现缩放到最大时（1600%）边缘就是正常的，所以极有可能是看图软件导致的渐变色，渲染有问题。
> 
> 把用来测试的标签写了一个遍历色彩的代码，好像也没有看到边缘渐变的颜色...总结下是我闹了个乌龙，实在太抱歉了。

客气了。
这部分可能是我项目里面没描述清楚，这里具体说下转换后的png图片。

# png标签图片说明

**转换后的png图片，看起来是彩图，但实际上是单通道图像。**
1. 转换语义分割png图片时
每个像素的值，就是类别index。具体对应的类别，与设置中的类别顺序是一致的；另外，在语义分割标签转换时，也会输出一个对应的类别与index的对应文件classesition.txt

2. 转换实例分割png图片时
每个像素的值，就是实例id。实例id顺序与标注时指定的组id一致。

# 具体使用
在训练与测试时，可以直接读取像素值作为真实标签使用。

# 额外的单通道png图片说明
png图片可以是单通道也可以是三通道的

三通道的png图片就是常说的rgb图片

单通道png彩图的实现是这样的，图片会包含单通道的矩阵，以及一份类似于字典一样的对应颜色关系。
- 单通道的矩阵，也就是这里的单通道图
- 颜色对应字典，存放了单通道图中存在的像素值对应的真实彩色。
两者搭配，可以通过单通道实现彩图的效果。

从这里也可以看出，**颜色只是外在表现，像素值才是最终的标签**

# png单通道图片像素值查看方法

为方便查看图像像素值，ISAT软件自带了显示像素值的功能。

- 对于rgb图片
当鼠标在图片上进行移动时，软件右下角会通过[R, G, B]格式，显示当前鼠标所在像素像素值。

- 对于单通道图(这里主要是转换后的png单通道标签图片)
当鼠标在图片上进行移动时，软件右下角会通过[I]格式，显示当前鼠标所在像素像素值。

**最后，欢迎使用ISAT，并多提出宝贵意见，ʕ̯•͡˔•̯᷅ʔ，多多支持哦！**

**Comment by mbkotori** [comment]
> > 太尴尬了。晚上重新检查了两遍，一次windows，一次linux上源码，才发现问题可能不是标签，是我的看图软件有问题。
> > windows上用的是win10自带的看图软件，然后用QQ截图的拾色器去读，一直有渐变色。
> > 后来第二遍用linux下Gwenview看图软件+Color Picker拾色器，发现缩放到最大时（1600%）边缘就是正常的，所以极有可能是看图软件导致的渐变色，渲染有问题。
> > 把用来测试的标签写了一个遍历色彩的代码，好像也没有看到边缘渐变的颜色...总结下是我闹了个乌龙，实在太抱歉了。
> 
> 客气了。 这部分可能是我项目里面没描述清楚，这里具体说下转换后的png图片。
> 
> # png标签图片说明
> **转换后的png图片，看起来是彩图，但实际上是单通道图像。**
> 
> 1. 转换语义分割png图片时
>    每个像素的值，就是类别index。具体对应的类别，与设置中的类别顺序是一致的；另外，在语义分割标签转换时，也会输出一个对应的类别与index的对应文件classesition.txt
> 2. 转换实例分割png图片时
>    每个像素的值，就是实例id。实例id顺序与标注时指定的组id一致。
> 
> # 具体使用
> 在训练与测试时，可以直接读取像素值作为真实标签使用。
> 
> # 额外的单通道png图片说明
> png图片可以是单通道也可以是三通道的
> 
> 三通道的png图片就是常说的rgb图片
> 
> 单通道png彩图的实现是这样的，图片会包含单通道的矩阵，以及一份类似于字典一样的对应颜色关系。
> 
> * 单通道的矩阵，也就是这里的单通道图
> * 颜色对应字典，存放了单通道图中存在的像素值对应的真实彩色。
>   两者搭配，可以通过单通道实现彩图的效果。
> 
> 从这里也可以看出，**颜色只是外在表现，像素值才是最终的标签**
> 
> # png单通道图片像素值查看方法
> 为方便查看图像像素值，ISAT软件自带了显示像素值的功能。
> 
> * 对于rgb图片
>   当鼠标在图片上进行移动时，软件右下角会通过[R, G, B]格式，显示当前鼠标所在像素像素值。
> * 对于单通道图(这里主要是转换后的png单通道标签图片)
>   当鼠标在图片上进行移动时，软件右下角会通过[I]格式，显示当前鼠标所在像素像素值。
> 
> **最后，欢迎使用ISAT，并多提出宝贵意见，ʕ̯•͡˔•̯᷅ʔ，多多支持哦！**

感谢解答！非常详细和清晰的解答，我之前还没注意到自带的像素查看功能hh,这个太方便了。

**Comment by yatengLG** [comment]
最近在开发一款新版本的ISAT，集成了segment anything。
只需要左右键点击目标，即可快速完成语义分割标注。并且没有丢失后续的多边形修改等功能。

有兴趣参与测试嘛ʕ̯•͡˔•̯᷅ʔ

**Comment by mbkotori** [comment]
> 最近在开发一款新版本的ISAT，集成了segment anything。 只需要左右键点击目标，即可快速完成语义分割标注。并且没有丢失后续的多边形修改等功能。
> 
> 有兴趣参与测试嘛ʕ̯•͡˔•̯᷅ʔ

没问题的！我github绑的邮箱不太常用一直没看到这条回复，太抱歉了。如果有机会我很乐意参加测试的

**Comment by yatengLG** [comment]
项目地址在这里：https://github.com/yatengLG/ISAT_with_segment_anything

基本已经完成了，标注效率还是挺高的。你可以试一试，欢迎提意见哦ʕ̯•͡˔•̯᷅ʔ
